###
GET http://localhost:5050/api/book/get-book
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0aW1lU3RhbXAiOjE2NzMxODAzOTYwMDEsInVzZXJOYW1lIjoibHZ6aGloZV8xMjNAcXEuY29tIn0.88ZEdBQGZyuCcfsBy2-bLosbjh0GU5Si1TsH7dHl2Js