###
POST http://localhost:5050/api/user/login
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="userName"
Content-Type: text/plain

lvzhihe_123@qq.com
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

prwq0421

<> 2023-01-08T202133.200.json